insert into artist values (2221, 'Suba/Lima, Marina', NULL);
insert into artist values (2222, 'Asher', 'Phil');
insert into artist values (2223, 'Suba/BiD/Katia B', NULL);
insert into artist values (2224, 'Funky Lowlives, The', NULL);
insert into artist values (2225, 'Taciana and Apollo 9', NULL);
insert into artist values (2226, 'Bigga Bush', NULL);
insert into artist values (2227, 'Juryman', NULL);
insert into artist values (2228, 'Moreira', 'Wilson');
insert into artist values (2229, 'Moreira', 'Wilson/Guarda Da Portela, Velha');
insert into artist values (2230, 'Monarco', NULL);
insert into artist values (2231, 'Guarda Da Portela', 'Cristina, Manacea, Monarco, Velha');
insert into artist values (2232, 'Cristina', NULL);
insert into artist values (2233, 'Pinheiro', 'Paulo Cesar and Cristina');
insert into artist values (2234, 'Moreira', 'Wilson/Pagodinho, Zeca');
insert into artist values (2235, 'da Vila', 'Luiz Carlos');
insert into artist values (2236, 'da Vila', 'Luiz Carlos/Moreira, Wilson');
insert into artist values (2237, 'Psychadelic Furs', NULL);
insert into artist values (2238, 'Genesis', NULL);
insert into artist values (2239, 'Boston', NULL);
insert into artist values (2240, 'Prince and the New Power Generation', NULL);
insert into artist values (2241, 'Ono', 'Yoko');
insert into artist values (2242, 'Cars, The', NULL);
insert into artist values (2243, 'Meat Loaf', NULL);
insert into artist values (2244, 'McNally', 'Shannon');
insert into artist values (2245, 'Brightman', 'Sarah and The London Symphony Orchestra');
insert into artist values (2246, 'Original Dixieland Jazz Band, The', NULL);
insert into artist values (2247, 'Williams', 'Clarence Blue Five');
insert into artist values (2248, 'Mingus', 'Charlie Jazz Workshop');
insert into artist values (2249, 'Ellington', 'Duke');
rem insert into artist values (2250, 'Davis', 'Miles');
insert into artist values (2251, 'Mahavishnu Orchestra', NULL);
insert into artist values (2252, 'Weather Report', NULL);
insert into artist values (2253, 'Bennett', 'Tony');
insert into artist values (2254, 'Marsalis', 'Branford Trio');
insert into artist values (2255, 'Fisk Jubilee Singers', NULL);
insert into artist values (2256, 'Smith', 'Mamie and Her Jazz Hounds');
insert into artist values (2257, 'Phillips', 'Washington');
insert into artist values (2258, 'Carr', 'Leroy/Blackwell, Scrapwell');
insert into artist values (2259, 'Dorsey', 'Thomas A.');
insert into artist values (2260, 'McTell', 'Blind Willie');
insert into artist values (2261, 'Leadbelly', NULL);
insert into artist values (2262, 'Broonzy', 'Big Bill');
insert into artist values (2263, 'White', 'Joshua');
insert into artist values (2264, 'Ives', 'Burl');
insert into artist values (2265, 'Robeson', 'Paul');
insert into artist values (2266, 'Williams', 'Big Joe');
insert into artist values (2267, 'Tucker', 'Ira and The Dixie Hummingbirds');
insert into artist values (2268, '(CBS) Trumpeteers, The', NULL);
insert into artist values (2269, 'Jackson', 'Mahalia');
insert into artist values (2270, 'Brothers Four, The', NULL);
insert into artist values (2271, 'Squirrel Nut Zippers', NULL);
insert into artist values (2272, 'Mitchell', 'Joni');
insert into artist values (2273, 'Osbourne', 'Jeffery');
insert into artist values (2274, 'Jane''s Addiction', NULL);
insert into artist values (2275, 'Kid Rock', NULL);
insert into artist values (2276, 'Zydeco', 'Buckwheat');
insert into artist values (2277, 'Rise', NULL);
insert into artist values (2278, 'Prine', 'John');
insert into artist values (2279, 'Lovett', 'Lyle');
insert into artist values (2280, 'Mr. Scruff', NULL);
insert into artist values (2281, 'Gray', 'David');
insert into artist values (2282, 'Reed', 'Francine');
insert into artist values (2283, 'Jones', 'Norah');
insert into artist values (2284, 'Lynch', 'Claire');
insert into artist values (2285, 'Thomas', 'Suzanne');
insert into artist values (2286, 'Bell', 'Delia');
insert into artist values (2287, 'Dickens', 'Hazel/Gerrard, Alice');
insert into artist values (2288, 'Vincent', 'Rhonda');
insert into artist values (2289, 'Cox Family', NULL);
insert into artist values (2290, 'Dickens', 'Hazel/Hawker, Ginny');
insert into artist values (2291, 'Cooper', 'Wilma Lee');
insert into artist values (2292, 'Dickens', 'Hazel');
insert into artist values (2293, 'Kallic', 'Kathy/Lewis, Laurie');
insert into artist values (2294, 'Morris', 'Lynn');
insert into artist values (2295, 'Krauss', 'Alison');
insert into artist values (2297, 'Hawker', 'Ginny/Jones, Carol Elizabeth');
insert into artist values (2296, 'Stevens Sisters, The', NULL);
insert into artist values (2298, 'Lewis', 'Laurie');
insert into artist values (2299, 'Cox Family, The/Krauss, Alison', NULL);
insert into artist values (2300, 'Boyens', 'Phyllis');
insert into artist values (2301, 'Jones', 'Carol Elizabeth');
insert into artist values (2302, 'Lewis/Lynch/Morris/Vincent', NULL);
insert into artist values (2303, 'Blind Boys of Alabama, The', NULL);
insert into artist values (2304, 'Del Rubio Triplets, The', NULL);
insert into artist values (2305, 'Beck Bogert Appice', NULL);
insert into artist values (2306, 'Radio Zumbido', NULL);
insert into artist values (2307, 'Cheap Trick', NULL);
insert into artist values (2308, 'Kottke', 'Leo/Gordon, Mike');
insert into artist values (2309, 'Creole Zydeco Farmers, The', NULL);
insert into artist values (2310, 'Frank', 'Keith and The Soileau Zydeco Band');
insert into artist values (2311, 'Ledet', 'Rosie');
insert into artist values (2312, 'Jocque', 'Beau');
insert into artist values (2313, 'Nathan and the Zydeco Cha Chas', NULL);
insert into artist values (2314, 'Taylor', 'Jude and His Burning Flames');
insert into artist values (2315, 'Chavis', 'Boozoo');
insert into artist values (2316, 'Queen Ida and Her Zydeco Band', NULL);
insert into artist values (2317, 'Delafose', 'Geno and French Rockin'' Boogie');
insert into artist values (2318, 'Joe K K and Zydeco Force', NULL);
insert into artist values (2319, 'Ardoin', 'Chris and Double Clutchin''');
insert into artist values (2320, 'Wilco', NULL);
insert into artist values (2321, 'Sanko', 'Erik');
insert into artist values (2322, 'Psyco On Da Bus', NULL);
insert into artist values (2323, 'Cafe Tacuba', NULL);
insert into artist values (2324, 'Mayfield', 'Irvin/Parks, Gordon');
insert into artist values (2325, 'Peru Negro', NULL);
insert into artist values (2326, 'Gigi', NULL);
insert into artist values (2327, 'Roots, The', NULL);
insert into artist values (2328, 'Martin', 'Steve');
insert into artist values (2329, 'Headhunters', NULL);
insert into artist values (2330, 'Lightnin Rod and the Thunderbolts', NULL);
insert into artist values (2331, 'Williams', 'Robin (comedian)');
insert into artist values (2332, 'Brown Sox', NULL);
insert into artist values (2333, 'Mann', 'Rickie');
insert into artist values (2334, 'Mayer', 'John');
insert into artist values (2335, 'Brindell', 'Sarah');
insert into artist values (2336, 'Sensus', NULL);
insert into artist values (2337, 'Sutrobath', NULL);
insert into artist values (2338, 'Spike Ivory', NULL);
insert into artist values (2339, 'Lecole', 'Scott');
insert into artist values (2340, 'Amberjack Rick', NULL);
insert into artist values (2341, 'Ditch', NULL);
insert into artist values (2342, 'Trible', 'Richard');
insert into artist values (2343, 'Workman', 'Tim');
insert into artist values (2344, 'Sista T', NULL);
insert into artist values (2345, 'Knapp', 'Katie');
insert into artist values (2346, 'Rosati', 'Felicia');
insert into artist values (2347, 'McClellan', 'John');
insert into artist values (2348, 'Toy', 'Sytlvia');
insert into artist values (2349, 'Surfadelics, The', NULL);
insert into artist values (2350, 'Dobric', 'Jimmy/Branham, Barry');
insert into artist values (2351, 'Freax', NULL);
insert into artist values (2352, 'Taba', NULL);
insert into artist values (2353, 'Ethan', NULL);
insert into artist values (2354, 'Bliss', 'Cheryl');
insert into artist values (2355, 'TV For Dogs', NULL);
insert into artist values (2356, 'Ivory Tower Project, The', NULL);
insert into artist values (2357, 'Rockidle', NULL);
insert into artist values (2358, 'El Sob', NULL);
insert into artist values (2359, 'Random Thoughts', NULL);
insert into artist values (2360, 'Mason', 'Ray Band');
insert into artist values (2361, 'Echo Beach', NULL);
insert into artist values (2362, 'Elliott', 'Jen');
insert into artist values (2363, 'Misspent Life', NULL);
insert into artist values (2364, 'Mr. Gone', NULL);
insert into artist values (2365, 'Pushing Red Buttons', NULL);
insert into artist values (2366, 'Gargantua Soul', NULL);
insert into artist values (2367, 'Mappari', NULL);
insert into artist values (2368, 'Pica', 'Tony');
insert into artist values (2369, 'Williams', 'Kevin');
insert into artist values (2370, 'Herzig', 'Monika Acoustic Project');
insert into artist values (2371, 'Living Space', NULL);
insert into artist values (2372, 'Dream Of Icarus', NULL);
insert into artist values (2373, 'Hyaline', NULL);
insert into artist values (2374, 'Psychedelic Breakfast, The', NULL);
insert into artist values (2375, 'Killing Season', NULL);
insert into artist values (2376, 'Koller', 'Markus');
insert into artist values (2377, 'Invertebrates', NULL);
insert into artist values (2378, 'Root Deco', NULL);
insert into artist values (2379, 'Byrds, The', NULL);
insert into artist values (2380, 'Soultree', NULL);
insert into artist values (2381, 'French', 'David');
insert into artist values (2382, 'Seewald', 'Zahava');
insert into artist values (2383, 'Klezmatics / Albertstein, Chava', NULL);
insert into artist values (2384, 'Cooder', 'Ry / Galban, Manuel');
insert into artist values (2385, '12 Pearls', NULL);
insert into artist values (2386, 'Aubele', 'Federico');
insert into artist values (2387, 'Los Hommes', NULL);
insert into artist values (2388, 'Ursula 1000', NULL);
insert into artist values (2389, 'Sofa Surfers', NULL);
insert into artist values (2390, 'Blue States', NULL);
insert into artist values (2391, 'Karminsky Experience, The', NULL);
insert into artist values (2392, 'Thunderball vs. Liftoff', NULL);
insert into artist values (2393, 'Williams', 'Desmond');
insert into artist values (2394, 'Thunderball', NULL);
insert into artist values (2395, 'Arkestra One', NULL);
insert into artist values (2396, 'Renevators, The', NULL);
insert into artist values (2397, 'Wray', 'Paulson');
insert into artist values (2398, 'Glassmaster', NULL);
insert into artist values (2399, 'Baaz', 'Frankie');
insert into artist values (2400, 'Fishkill', NULL);
insert into artist values (2401, 'Madaris', 'Sandy');
insert into artist values (2402, 'Nickel Creek', NULL);
insert into artist values (2403, '3rd Force', NULL);
insert into artist values (2404, 'van der Scafe', 'Melissa');
insert into artist values (2405, 'On Tracy Lane', NULL);
insert into artist values (2406, 'Modest Mouse', NULL);
insert into artist values (2407, 'Hill', 'Leandra');
insert into artist values (2408, 'Stattica', NULL);
insert into artist values (2409, 'Girly Freak Show', NULL);
insert into artist values (2410, 'Jewel', NULL);
insert into artist values (2411, 'Prospect Place', NULL);
insert into artist values (2412, 'al-Saher', 'Kazem');
insert into artist values (2413, 'Tenacious D', NULL);
insert into artist values (2414, 'Bragg', 'Billy');
insert into artist values (2415, 'Rose', 'Adrian');
insert into artist values (2416, 'Collider', NULL);
insert into artist values (2417, '13 Flowers', NULL);
insert into artist values (2418, 'Wood', 'Dave');
insert into artist values (2419, 'Pink', NULL);
insert into artist values (2420, 'Redbone', 'Martha');
insert into artist values (2421, 'GrooveLily', NULL);
insert into artist values (2422, 'Denhert', 'KJ');
insert into artist values (2423, 'Molly Hatchet', NULL);
insert into artist values (2424, 'Jacks, The', NULL);
insert into artist values (2425, 'Andrews', 'Lee and the Hearts');
insert into artist values (2426, 'Little Anthony and The Imperials', NULL);
insert into artist values (2427, 'Mystics, The', NULL);
insert into artist values (2428, 'Randy and the Rainbows', NULL);
insert into artist values (2429, 'Jay and the Americans', NULL);
insert into artist values (2430, 'Texas Tornados', NULL);
insert into artist values (2431, 'Matthew Show, The', NULL);
insert into artist values (2432, 'Clancy Brothers and Tommy Makem, The', NULL);
insert into artist values (2433, 'New Christy Minstrels, The', NULL);
insert into artist values (2434, 'Seeger', 'Pete');
insert into artist values (2435, 'House', 'Son');
insert into artist values (2436, 'Reynolds', 'Malvina');
insert into artist values (2437, 'Mahal', 'Taj');
insert into artist values (2438, 'Rush', 'Tom');
insert into artist values (2439, 'Winter', 'Johnny');
insert into artist values (2440, 'Anderson', 'Eric');
insert into artist values (2441, 'Fogelberg', 'Dan');
insert into artist values (2442, 'Forbert', 'Steve');
insert into artist values (2443, 'Colvin', 'Shawn');
insert into artist values (2444, 'Caesar', 'Shirley');
insert into artist values (2445, 'Carson', 'Fiddlin'' John');
insert into artist values (2446, 'Bumgarner', 'Samantha');
insert into artist values (2447, 'Tanner', 'Gid and His Skillet Lickers');
insert into artist values (2448, 'Miller', 'Emmett');
insert into artist values (2449, 'Reeves', 'Goebel');
insert into artist values (2450, 'Montana', 'Patsy and the Prairie Ramblers');
insert into artist values (2451, 'Acuff', 'Roy and His Crazy Tennesseans');
insert into artist values (2452, 'Chuck Wagon Gang, The', NULL);
insert into artist values (2453, 'Sons of the Pioneers', NULL);
insert into artist values (2454, 'Wills', 'Bob and His Texas Playboys');
insert into artist values (2455, 'Daffan', 'Ted''s Texans');
insert into artist values (2456, 'Dexter', 'Al and His Troopers');
insert into artist values (2457, 'Monroe', 'Bill and His Blue Grass Boys');
insert into artist values (2458, 'Tillman', 'Floyd');
insert into artist values (2459, 'Stanley Brothers', NULL);
insert into artist values (2460, 'Dickens', 'Little Jimmy');
insert into artist values (2461, 'Frizzell', 'Lefty');
insert into artist values (2462, 'Smith', 'Carl');
insert into artist values (2463, 'Price', 'Ray');
insert into artist values (2464, 'Collins Kids, The', NULL);
insert into artist values (2465, 'Horton', 'Johnny');
insert into artist values (2466, 'Robbins', 'Marty');
insert into artist values (2467, 'Hall', 'Roy and His Blue Ridge Entertainers');
insert into artist values (2468, 'Dean', 'Jimmy');
insert into artist values (2469, 'Staler Brothers, The', NULL);
insert into artist values (2470, 'Flatt and Scruggs', NULL);
insert into artist values (2471, 'Houston', 'David');
insert into artist values (2472, 'Wynette', 'Tammy');
insert into artist values (2473, 'Kristofferson', 'Kris');
insert into artist values (2474, 'Rich', 'Charlie');
insert into artist values (2475, 'Tucker', 'Tanya');
insert into artist values (2476, 'Nelson', 'Willie');
insert into artist values (2477, 'Jones', 'George / Wynette, Tammy');
insert into artist values (2478, 'Paycheck', 'Johnny');
insert into artist values (2479, 'Daniels', 'Charlie Band, The');
insert into artist values (2480, 'Jones', 'George');
insert into artist values (2481, 'Cash', 'Rosanne');
insert into artist values (2482, 'Skaggs', 'Ricky');
insert into artist values (2483, 'Nelson', 'Willie / Haggard, Merle');
insert into artist values (2484, 'Crowell', 'Rodney');
insert into artist values (2485, 'Carpenter', 'Mary Chapin');
insert into artist values (2486, 'Loveless', 'Patty');
insert into artist values (2487, 'Diffie', 'Joe');
insert into artist values (2488, 'Dixie Chicks', NULL);
insert into artist values (2489, 'Young', 'Charlie');
insert into artist values (2490, 'West', 'Mae');
insert into artist values (2491, 'Durante', 'Jimmy');
insert into artist values (2492, 'Powell', 'Dick');
insert into artist values (2493, 'Astaire', 'Fred');
insert into artist values (2494, 'Day', 'Doris');
insert into artist values (2495, 'Garland', 'Judy');
insert into artist values (2496, 'Warner Brothers Orchestra and Chorus, The', NULL);
insert into artist values (2497, 'Miller', 'Mitch, His Orchestra and Chorus');
insert into artist values (2498, 'Damonte', 'Vic');
insert into artist values (2499, 'Mathis', 'Johnny');
insert into artist values (2500, 'Monroe', 'Marilyn');
insert into artist values (2501, 'Green', 'Johnny, Orchestra Conducted By');
insert into artist values (2502, 'Holloway', 'Stanley and Ensemble');
insert into artist values (2503, 'Lulu', NULL);
insert into artist values (2504, 'Diamond', 'Neil');
insert into artist values (2505, 'Streisand', 'Barbra');
insert into artist values (2506, 'Cafferty', 'John and the Beaver Brown Band');
insert into artist values (2507, 'Loggins', 'Kenny');
insert into artist values (2508, 'Berlin', NULL);
insert into artist values (2509, 'Barry', 'John, Orchestra Conducted By');
insert into artist values (2510, 'Pearl Jam', NULL);
insert into artist values (2511, 'Dion', 'Celine / Griffin, Clive');
insert into artist values (2512, 'Silversti', 'Alan, Orchestra Conducted By');
insert into artist values (2513, 'Jackson', 'Michael');
insert into artist values (2514, 'Refugee Camp All-Stars', NULL);
insert into artist values (2515, 'Smith', 'Wil');
insert into artist values (2516, 'King', 'Diana');
insert into artist values (2517, 'Horner', 'James, Orchestra Conducted By');
insert into artist values (2518, 'Dion', 'Celine');
insert into artist values (2519, 'Aerosmith', NULL);
insert into artist values (2520, 'Morgen', 'Helen');
insert into artist values (2521, 'Bruce', 'Carol / Dowdy, Helen / Spencer, Kenneth and Chorus');
insert into artist values (2522, 'Logan', 'Ella');
insert into artist values (2523, 'Drake', 'Alfred / Morison, Patricia');
insert into artist values (2524, 'Pinza', 'Ezio');
insert into artist values (2525, 'Martin', 'Mary Girls'' Chorus');
insert into artist values (2526, 'Channing', 'Carol');
insert into artist values (2527, 'Morrow', 'Doretta / Kiley, Richard');
insert into artist values (2528, 'Riatt', 'John');
insert into artist values (2529, 'Haney', 'Carol and Ensemble');
insert into artist values (2530, 'Harrison', 'Rex / Andrews, Julie / Coote, Robert');
insert into artist values (2531, 'Andrews', 'Julie / Bevan, Phillipa');
insert into artist values (2532, 'Harrison', 'Rex');
insert into artist values (2533, 'Holliday', 'Judy');
insert into artist values (2534, 'Kert', 'Larry / Lawrence, Carol');
insert into artist values (2535, 'Rivera', 'Chita and Girls');
insert into artist values (2536, 'Russell', 'Rosalind');
insert into artist values (2537, 'Suzuki', 'Pat');
insert into artist values (2538, 'Merman', 'Ethel');
insert into artist values (2539, 'Segal', 'Vivienne');
insert into artist values (2540, 'Martin', 'Mary / Neway, Patricia');
insert into artist values (2541, 'Martin', 'Mary');
insert into artist values (2542, 'Van Dyke', 'Dick');
insert into artist values (2543, 'Burton', 'Richard');
insert into artist values (2544, 'Remick', 'Lee');
insert into artist values (2545, 'Allen', 'Elizabeth');
insert into artist values (2546, 'Gallagher', 'Helen / Oliver, Thelma');
insert into artist values (2547, 'Braswell', 'Charles');
insert into artist values (2548, 'Grey', 'Joel');
insert into artist values (2549, 'Haworth', 'Jill');
insert into artist values (2550, 'Stritch', 'Elaine');
insert into artist values (2551, 'Gilford', 'Jack / Watson, Susan');
insert into artist values (2552, 'Johns', 'GLynis');
insert into artist values (2553, 'Lopez', 'Priscilla');
insert into artist values (2554, 'McArdle', 'Andrea');
insert into artist values (2555, 'Montevecchi', 'Liliane / Cotsirilos, Shephanie');
insert into artist values (2556, 'Carradine', 'Keith');
insert into artist values (2557, 'Isaacs', 'Pamela / White, Lillias');
insert into artist values (2558, 'Laine', 'Frankie');
insert into artist values (2559, 'Clooney', 'Rosemary');
insert into artist values (2560, 'Ray', 'Johnnie and the Four Lads');
insert into artist values (2561, 'Miller', 'Mitch');
insert into artist values (2562, 'Four Lads, The', NULL);
insert into artist values (2563, 'Mitchell', 'Guy');
insert into artist values (2564, 'Jamies, The', NULL);
insert into artist values (2565, 'Faith', 'Percy');
insert into artist values (2566, 'Williams', 'Andy');
insert into artist values (2567, 'Orlando', 'Tony');
insert into artist values (2568, 'Vinton', 'Bobby');
insert into artist values (2569, 'Dion', NULL);
insert into artist values (2570, 'Major Lance', NULL);
insert into artist values (2571, 'Rip Chords, The', NULL);
insert into artist values (2572, 'Chad and Jeremy', NULL);
insert into artist values (2573, 'Royal', 'Billy Joe');
insert into artist values (2574, 'Stafford', 'Jo');
insert into artist values (2575, 'Cabas', NULL);
insert into artist values (2576, 'Dashboard Confessional', NULL);
insert into artist values (2577, 'Blur', NULL);
insert into artist values (2578, 'Alves', 'Paul');
insert into artist values (2579, 'King Orba', NULL);
insert into artist values (2580, 'PrimeTime Sublime Community Orchestra, The', NULL);
insert into artist values (2581, 'Broken Ness', NULL);
insert into artist values (2582, 'Kontora Kooka', NULL);
insert into artist values (2583, 'Cole', 'Aaron');
insert into artist values (2584, 'Seven 13', NULL);
insert into artist values (2585, 'Uncle Fucker', NULL);
insert into artist values (2586, 'Outkast', NULL);
insert into artist values (2587, 'Moore', 'Joseph Patrick''s Drum and Bass Society');
insert into artist values (2588, 'Compton', 'Kathy');
insert into artist values (2589, 'Leiana', NULL);
insert into artist values (2590, 'Wray', 'Grayson');
insert into artist values (2591, 'Andersson', 'Theresa');
insert into artist values (2592, 'Chemistry', NULL);
insert into artist values (2593, 'Shimatani', 'Hitomi');
insert into artist values (2594, 'Parker', 'Andrea');
insert into artist values (2595, 'Cranberries, The', NULL);
insert into artist values (2596, 'Apple', 'Fiona');
insert into artist values (2597, 'Lavigne', 'Avril');
insert into artist values (2598, 'Papa Roach', NULL);
insert into artist values (2599, 'Crow', 'Sheryl');
insert into artist values (2600, 'Mile 8', NULL);
insert into artist values (2601, 'Morrissey', NULL);
insert into artist values (2602, 'Bare', 'Bobby Jr''s Young Criminals'' Starvation League');
insert into artist values (2603, 'Stereo 360', NULL);
insert into artist values (2604, 'Valerian', NULL);
insert into artist values (2605, 'Dipsomaniacs', NULL);
insert into artist values (2606, 'Loggins', 'Kenny / Messina, Jim');
insert into artist values (2607, 'Hunter', 'Ian');
insert into artist values (2608, 'Boyter', 'Ann');
insert into artist values (2609, 'BMG 44', NULL);
insert into artist values (2610, 'Omzo', NULL);
insert into artist values (2611, 'Shiffai', NULL);
insert into artist values (2612, 'Las MC', NULL);
insert into artist values (2613, 'Simon (Bis Bi Klan)', NULL);
insert into artist values (2614, 'Sul Suli Klan', NULL);
insert into artist values (2615, 'Slam Revolution', NULL);
insert into artist values (2616, 'Sen Kumpa', NULL);
insert into artist values (2617, 'Abass', NULL);
insert into artist values (2618, 'Real Fight', NULL);
insert into artist values (2619, 'Yat Fu', NULL);
insert into artist values (2620, 'Winter', 'Edgar and Johnny');
insert into artist values (2621, 'King', 'B.B.');
insert into artist values (2622, 'Miserable', 'Joey and the Worms');
insert into artist values (2623, 'RuPaul', NULL);
insert into artist values (2624, 'Howard', 'Rosetta');
insert into artist values (2625, 'Jackson', 'Bessie');
insert into artist values (2626, 'Alexaner', 'Ora');
insert into artist values (2627, 'Carter', 'Bo');
insert into artist values (2628, 'Chicago Black Swans, The', NULL);
insert into artist values (2629, 'Johnson', 'Lil');
insert into artist values (2630, 'Fletcher', 'Napolean');
insert into artist values (2631, 'Dallas Jug Band, The', NULL);
insert into artist values (2632, 'Foote', 'Bea');
insert into artist values (2633, 'Temple', 'Johnny');
insert into artist values (2634, 'Fuller', 'Blind Boy');
insert into artist values (2635, 'Cyrkle, The', NULL);
insert into artist values (2636, 'Donovan', NULL);
insert into artist values (2637, 'Buckinghams, The', NULL);
insert into artist values (2638, 'McKenzie', 'Scott');
insert into artist values (2639, 'Small Faces', NULL);
insert into artist values (2640, 'Nyro', 'Laura');
insert into artist values (2641, 'Union Gap, The', NULL);
insert into artist values (2642, 'Swan', 'Billy');
insert into artist values (2643, 'Remains, The', NULL);
insert into artist values (2644, 'Moby Grape', NULL);
insert into artist values (2645, 'Chamber Brothers, The', NULL);
insert into artist values (2646, 'Beck', 'Jeff');
insert into artist values (2647, 'Spirit', NULL);
insert into artist values (2648, 'Iggy and the Stooges', NULL);
insert into artist values (2649, 'Kansas', NULL);
insert into artist values (2650, 'Blue Oyster Cult', NULL);
insert into artist values (2651, 'Nugent', 'Ted');
insert into artist values (2652, 'Heart', NULL);
insert into artist values (2653, 'Meatloaf', NULL);
insert into artist values (2654, 'Judas Priest', NULL);
insert into artist values (2655, 'Living Colour', NULL);
insert into artist values (2656, 'Soul Asylum', NULL);
insert into artist values (2657, 'Rage Against The Machine', NULL);
insert into artist values (2658, 'Korn', NULL);
insert into artist values (2659, 'Ravens, The', NULL);
insert into artist values (2660, 'Treniers, The', NULL);
insert into artist values (2661, 'Willis', 'Chuck and the Royals');
insert into artist values (2662, 'Big Maybelle', NULL);
insert into artist values (2663, 'Hawkins', 'Screamin'' Jay');
insert into artist values (2664, 'Hamilton', 'Roy');
insert into artist values (2665, 'Jackson', 'Walter');
insert into artist values (2666, 'Riperton', 'Minnie');
insert into artist values (2667, 'Melvin', 'Harold and the Blue Notes');
insert into artist values (2668, 'Manhattans, The', NULL);
insert into artist values (2669, 'Jacksons, The', NULL);
insert into artist values (2670, 'Emotions, The', NULL);
insert into artist values (2671, 'Lynn', 'Cheryl');
insert into artist values (2672, 'Vandross', 'Luther');
insert into artist values (2673, 'Mtume', NULL);
insert into artist values (2674, 'Teena Marie', NULL);
insert into artist values (2675, 'Lisa Lisa and Cult Jam w/Full Force', NULL);
insert into artist values (2676, 'L.L. Cool J', NULL);
insert into artist values (2677, 'Public Enemy', NULL);
insert into artist values (2678, 'Belle', 'Regina');
insert into artist values (2679, 'C+C Music Factory', NULL);
insert into artist values (2680, 'Kriss Kross', NULL);
insert into artist values (2681, 'Xscape', NULL);
insert into artist values (2682, 'Babyface', NULL);
insert into artist values (2683, 'Carey', 'Mariah');
insert into artist values (2684, 'Maxwell', NULL);
insert into artist values (2685, 'NAS', NULL);
insert into artist values (2686, 'Bone Thugs-N-Harmony', NULL);
insert into artist values (2687, 'Fugees, The', NULL);
insert into artist valueS (2688, 'Ginuwine', NULL);
insert into artist values (2689, 'Chicago', NULL);
insert into artist values (2690, 'Nash', 'Johnny');
insert into artist values (2691, 'Thompson', 'Robbin Band, The');
insert into artist values (2692, 'Time, The', NULL);
insert into artist values (2693, 'Rifkin', 'Joshua');
insert into artist values (2694, 'Halovox', NULL);
insert into artist values (2695, 'Synodinos', 'Jean');
insert into artist values (2696, 'Minutemen, The', NULL);
insert into artist values (2697, 'Long Ryders, The', NULL);
insert into artist values (2698, 'Alisa', NULL);
insert into artist values (2699, 'Savage Republic', NULL);
insert into artist values (2700, 'Animal Dance', NULL);
insert into artist values (2701, 'Albertano', 'Linda J.');
insert into artist values (2702, 'Three O''Clock, The', NULL);
insert into artist values (2703, '100 Flowers', NULL);
insert into artist values (2704, 'Bay of Pigs', NULL);
insert into artist values (2705, 'Shadow Minstrels', NULL);
insert into artist values (2706, 'Phranc', NULL);
insert into artist values (2707, '17 Pygmies', NULL);
insert into artist values (2708, 'Bangles, The', NULL);
insert into artist values (2709, 'Beef Sisters, The', NULL);
insert into artist values (2710, 'Raid Parade', NULL);
insert into artist values (2711, 'Wednesday Week', NULL);
insert into artist values (2712, 'Pop Art', NULL);
insert into artist values (2713, 'Fibonaccis', NULL);
insert into artist values (2714, 'Copeland', 'Stewart / Holt, Derek');
insert into artist values (2715, 'Alarm, The', NULL);
insert into artist values (2716, 'General Public', NULL);
insert into artist values (2718, 'Go-Go''s', NULL);
insert into artist values (2719, 'Squeeze', NULL);
insert into artist values (2720, 'Johnson', 'Omega');
insert into artist values (2721, 'Van Overmeire', 'Mark');
insert into artist values (2722, 'Pimp Tea', NULL);
insert into artist values (2723, 'Harris', 'Herb');
insert into artist values (2724, 'Liquid Blue', NULL);
insert into artist values (2725, 'McDonough', 'Larry');
insert into artist values (2726, 'Style Council, The', NULL);
insert into artist values (2727, 'Rush', NULL);
insert into artist values (2728, 'Bonds', 'Gary U.S.');
insert into artist values (2729, 'Nails, The', NULL);
insert into artist values (2730, 'Adams', 'Christian');
insert into artist values (2731, 'Franz Ferdinand', NULL);
insert into artist values (2732, 'Holt', 'Mark / Holt Tully, Kimberlee');
insert into artist values (2733, 'Mayone', 'Steve');
insert into artist values (2734, 'Screens, The', NULL);
insert into artist values (2735, 'Eminem', NULL);
insert into artist values (2736, 'Temmerman', 'John''s Jazz Obsession Quartet');
insert into artist values (2737, 'DeAdder', 'Lou');
insert into artist values (2738, 'Four Bags, The', NULL);
insert into artist values (2739, 'Bates', 'Janet');
insert into artist values (2740, 'Green Day', NULL);
insert into artist values (2741, 'Brass Knuckle Surfer', NULL);
insert into artist values (2742, 'Hirt', 'Al');
insert into artist values (2743, 'Hamilton', 'Chico Quintet');
insert into artist values (2744, 'Marvellettes, The', NULL);
insert into artist values (2745, 'Supremes, The', NULL);
insert into artist values (2747, 'Four Tops, The', NULL);
insert into artist values (2748, 'Kendricks', 'Eddie');
insert into artist values (2749, 'Robinson', 'Smokey and the Miracles');
insert into artist values (2750, 'Houston', 'Thelma');
insert into artist values (2751, 'James', 'Rick');
insert into artist values (2752, 'Ross', 'Diana / Richie, Lionel');
insert into artist values (2753, 'Khan', 'Ustad Rais / Khan, Ustad Sultan');
insert into artist values (2754, 'Brecker', 'Michael');
insert into artist values (2755, 'Williams', 'Mary Lou');
insert into artist values (2756, 'Bolin', 'Tommy');
insert into artist values (2757, 'Byrd', 'Charlie');
insert into artist values (2758, 'Psycho Versatile', NULL);
insert into artist values (2759, 'Ruffins', 'Kermit with the Rebirth Brass Band');
insert into artist values (2760, 'Jazz Mandolin Project', NULL);
insert into artist values (2761, 'Yonder Mountain String Band', NULL);
insert into artist values (2762, 'McCoury', 'The Del Band');
insert into artist values (2763, 'McCoury', 'The Del Band/Yonder Mountain String Band');
insert into artist values (2764, 'Michaels', 'Drayton');
insert into artist values (2765, 'OHN', NULL);
insert into artist values (2766, 'Interpol', NULL);
insert into artist values (2767, 'Plegg', NULL);
insert into artist values (2768, 'Sumitra', NULL);
insert into artist values (2769, 'Sykes', 'Roosevelt');
insert into artist values (2770, 'James', 'Elmore/Williamson, Sonny Boy');
insert into artist values (2771, 'Struck', 'Nolan');
insert into artist values (2772, 'Spann', 'Otis/Lockwoood, Robert Jr.');
insert into artist values (2773, 'Arnold', 'Billy Boy/Jones, Johnnie');
insert into artist values (2774, 'Wells', 'Junior');
insert into artist values (2775, 'Arnold', 'Billy Boy/Bishop, Elvin/Cotton, James');
insert into artist values (2776, 'Wellington', 'Valerie');
insert into artist values (2777, 'John', 'John Little');
insert into artist values (2778, 'Musselwhite', 'Charlie');
insert into artist values (2779, 'Clearwater', 'Eddy');
insert into artist values (2780, 'Walter', 'Little Johnny');
insert into artist values (2781, 'Magic Sam', NULL);
insert into artist values (2782, 'Skye', 'Eric');
